---
 - name: Update apt Packages
   become: true
   become_method: sudo
   apt:
     update_cache: yes

 - name: install node
   shell: |
     cd ~
     curl -sL https://deb.nodesource.com/setup_13.x -o /tmp/nodesource_setup.sh

 - name: run setup node
   become: true
   become_method: sudo
   shell: |
     bash /tmp/nodesource_setup.sh
     apt install -y nodejs


 - name: install pm2
   become: true
   become_method: sudo
   shell: |
     npm install pm2 -g