---
 - name: Run expect to wait for a successful PXE boot via out-of-band CIMC
   become: true
   become_method: sudo
   shell: |
     mkdir /var/www/html

 - name: "move backend gz"
   copy:
    src: artifact.tar.gz
    dest: /var/www/html/artifact.tar.gz
    backup: yes

 - name: extract
   shell: |
     cd /var/www/html
     tar -xvzf artifact.tar.gz

 - name: run project
   shell: |
     npm install
     pm2 stop default
     pm2 start npm -- start