---
 - name: Run expect to wait for a successful PXE boot via out-of-band CIMC
   become: true
   become_method: sudo
   shell: |
     mkdir /var/www
     sudo chown -R ubuntu:ubuntu /var/www
     sudo chmod 2775 /var/www

 - name: "move backend gz"
   become: true
   copy:
    src: artifact.tar.gz
    dest: /var/www/artifact.tar.gz
    backup: yes

 - name: extract
   shell: |
     cd /var/www
     tar -xvzf artifact.tar.gz

 - name: run project
   shell: |
     npm install
     pm2 stop default
     NODE_PORT=3030 pm2 start npm -- start
     PORT=3002 pm2 start npm -- start