---
- name: "move backend gz"
  copy:
    src: artifact.tar.gz
    dest: /var/www/html/artifact.tar.gz
    backup: yes

 - name: extract
   shell: |
     cd /var/www/html
      tar -xvzf artifact.tar.gz

 - name: run project
   shell: |
     npm install
     pm2 stop default
     pm2 start npm -- start